---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
    - containerPath: /etc/ssl/certs/ca-certificates.crt
      hostPath: %%LOCAL_CA_CERTS%%
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: %%LOCAL_IP%%
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    listenAddress: %%LOCAL_IP%%
    protocol: TCP
